### PR TITLE
Add zh_CN.lang

### PR DESCRIPTION
**Pull request by muink**
part translation text

### CODE REVIEW

**Comment by Vectron** [comment]
is it posible for you to do the translation on the 1.8 branch. there are alot more strings added to that version for translating.

**Comment by muink** [comment]
oh...are lang files in master branch is old?  Σ(⊙▽⊙"!!

**Comment by Vectron** [comment]
yes, masterbranch is for 1.7.10
i have seperate branches with lots of updates for 1.8+

**Comment by muink** [comment]
I have created a pull requests of 1.8 for the language file
and complete of this translation :+1:

**Pull request merged**
