### PR TITLE
Add ru_RU.lang, de_DE.lang, fr_FR.lang, pack.mcmeta

### PR DESCRIPTION
**Pull request by Adaptivity**
de_DE.lang was taken from https://github.com/daveyliam/mapwriter/pull/20 Credits goes to @Vexatos
fr_FR.lang was taken from https://github.com/daveyliam/mapwriter/pull/32 Credits goes to @Mazdallier
ru_RU.lang created by me :)

### CODE REVIEW

**Comment by Vexatos** [comment]
:+1:

**Comment by Mazdallier** [comment]
:@

**Comment by Vectron** [comment]
What kind of comment is that?

**Comment by Adaptivity** [comment]
I guess it's meant to be :2 :smile:

**Comment by Mazdallier** [comment]
Je suis bouche bé. I'm supprised

**Pull request merged**
