### PR TITLE
Change the event used to change the map dimension (fixes Mystcraft linking books).

### PR DESCRIPTION
**Pull request by EXTER7**
This PR changes the way the dimension is changed. It work's by handling the GUI open event and changing the map dimension when the "Downloading Terrain" screen appears. This fixes the dimension of the map changing prematurely when opening Mystcraft linking books, or any mod that uses the LookingGlass library.

### CODE REVIEW

**Comment by Vectron** [comment]
did you change any thing in these files? (cant find anything at a quick glace, so find it odd that they are added to the pr)
mapwriter/gui/MwGuiMarkerDialogNew.java
mapwriter/forge/ClientProxy.java
resources/mcmod.info

**Comment by EXTER7** [comment]
That's strange, I only changed 'mapwriter/Mw.java
' and 'mapwriter/forge/EventHandler.java
'. Don't know why they appear on the commit.

**Comment by EXTER7** [comment]
Removed the extra files from the commit.

**Comment by Vectron** [comment]
thanks, will do the merge this weekend when i'm back home.

**Pull request merged**
