### PR TITLE
Localization support for 1.7.10

### PR DESCRIPTION
**Pull request by Adaptivity**
Ported localization support to 1.7.10
Refreshed Gradle wrapper

P.S MwGuiMarkerDialogNew.java seems to be a bit messy (Github shows that it's fully changed but this is not true) but should be good.

### CODE REVIEW

**Comment by Vectron** [comment]
Does this make the localization the same as the 1.8 branch?

**Comment by Adaptivity** [comment]
Mostly, yes, just with some differences.

**Comment by Vectron** [comment]
do you know the differences?
if so i can make them the same in 1.8

**Comment by Adaptivity** [comment]
The first thing I didn't used *new Object[0]* in localized strings (I honestly don't know what this thing is doing in 1.8 branch) maybe I wrong though. And the second, I moved out some %s, %d tags out of code into .lang file. Minor change but this can help some translators (for example they can swap localization text with tag).

**Comment by Vectron** [comment]
the new object thing is just coping from minecraft code, they do that 2. but it's not needed.
i'll do some comparing to the 1.8 branch to make it the same and then merge your pull.

**Pull request merged**
